// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults
values: {
	message: "Hello World"
	image: {
		repository: "quay.io/poseidon/matchbox"
		digest:     ""
		tag:        "v0.9.1"
	}
	resources: {
		requests: {
			cpu:    "50m"
			memory: "32Mi"
		}
		limits: {
			cpu:    "50m"
			memory: "32Mi"
		}
	}
}
