ociRegistry:
    password: ENC[AES256_GCM,data:cP0Ua9Jt2aWUeonL+V69pMpN7mqVAqg/BNfQBBsB9j7tSC0Ycw6Kqg==,iv:R4dnyDFr13+g2OB5s6OeBdxVn1k8xH4jSEB4xKRK/Xc=,tag:sW0JeQ+urxh7RXmXYOIelw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-24T23:57:38Z"
    mac: ENC[AES256_GCM,data:K9uJcVfnAUE0PqFQfpkFE2ZqmDTINJQk1rS0PJxl7NFZIh1ZKuiHj7+dKFiCnUdLBan7RcpKKCIrc1hmSfxjOwqDJj2jcO0pklET6WmKIgNv4HvLXV3OS3pIKAdAHpRZPGXxzezvucC6uukPUmNuas+9zfbTMexXjkouEzY3ygs=,iv:L5mxMHV+6mqKPbrGzmcXgZegsdveIyh+KRBAfDOvHJc=,tag:ryhbqs2C4hBGcUBrh/O8Qg==,type:str]
    pgp:
        - created_at: "2024-02-24T23:57:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxtk/ur4aB3lAQ//fDp/J8T9VQ0o9zORuuTe1UOAoKSQbYpE5riaPFqS2+gs
            CfrGG6sBuAihbEnpwpfxmgxvyjN6oaJqSuPifiuv4EI+bIMgL85XUu7FY013ZDOb
            +Z8MBZ9DVIjTy6VulEBDYLWrClLdXtyf4YL2pztI59ENcM+P7DhywcbszEGjRi7n
            EOFqlLczfmx55gmzbFwMvSIIgBsDq510J3/9P/bkfHRajaViYJ9UzgK0y5rkaD3d
            h43vSrYDFVHjm6Zhscczn/csc4qMPRPtThh3g1xmdz4fXXpL+/GfX4ZrDIzvvNah
            ZNCXzY3SYTpSmvt4n5KBZdMW+Y/blRys75yccMCKEKEUYP/eljpCX8RPGscaZVo1
            TDp0DlINHp8m+wda9UQ4jE4AuFYm4Bv5uKlhE5STLkX16r8ai7EUJRtvmIkAGxik
            GUlZTJyY+f1c6fmfYH5LvWMhAzJIopObmV5ViyXIJiqX0syl6Vo9Jiz+MqU9kDxu
            o6L4EQL8ElFfQSr9PbcvwfdgvKtT2GNpa5JmMc6AhusPFqSN4j/xOcudY9CwTVxw
            qUGXwlEzpXh563mtTITAfFGLAHo5ekjEZoedoyfg9ob4tIG+vhNFRcgM+RcS9LiV
            Xfg8B5B1tKeTwUaNFQmyActwf0J+sOqcn8ay6ZbGr6j6kt2PJHkVY1QlT2W9w8bU
            ZgEJAhCbGJHzRbYSCCrhH1jdBqNXYOHLX/fT0/gun08DbDxvoIX0hh0R9eSgj7O6
            q8CCsNcOusk3AqFk7x/d0BeIVyT3yE1rjELBtjG26Wg115Z726ZnDuUHhTBfZTU+
            oPDAnEs+RA==
            =2hSz
            -----END PGP MESSAGE-----
          fp: 095FA4536EDECB97C43669C5A78ADDCFDA276CE5
    unencrypted_suffix: _unencrypted
    version: 3.8.1
